function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.22947502
    Base.precompile(Tuple{Core.kwftype(typeof(pretty_table)),NamedTuple{(:alignment, :crop), Tuple{Symbol, Symbol}},typeof(pretty_table),Vector{Any}})   # time: 0.11091652
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int8}})   # time: 0.09649028
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_latex)),NamedTuple{(:compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Val{:print}}},typeof(_parse_cell_latex),IOContext{Base.TTY},String})   # time: 0.068166025
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},AnsiTextCell})   # time: 0.05508074
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt16}})   # time: 0.054710362
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt16}})   # time: 0.050510608
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt32})   # time: 0.046821207
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Bool}})   # time: 0.046796013
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_latex)),NamedTuple{(:cell_first_line_only, :compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_latex),IOContext{Base.TTY},LatexCell{String}})   # time: 0.041356903
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt64}})   # time: 0.040075626
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int32}})   # time: 0.03836484
    Base.precompile(Tuple{typeof(_pt_html),IOContext{Base.TTY},PrintInfo})   # time: 0.037852198
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_html)),NamedTuple{(:header_cell_titles, :minify, :show_omitted_cell_summary, :standalone, :table_class, :table_div_class, :top_left_str, :top_right_str_decoration, :vcrop_mode, :wrap_table_in_div), Tuple{Tuple{Nothing, Vector{String}}, Bool, Bool, Bool, String, String, String, HtmlDecoration, Symbol, Bool}},typeof(_pt_html),IOContext{Base.TTY},PrintInfo})   # time: 0.03767096
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},String})   # time: 0.037216537
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Bool}})   # time: 0.0362744
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, Symbol, Vector{Int64}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.036197715
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:subheader_crayon,), Tuple{Vector{Crayon}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.035942923
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt32})   # time: 0.034853965
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:header_crayon,), Tuple{Vector{Crayon}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.03296546
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int16}})   # time: 0.030896664
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Float64}})   # time: 0.030082647
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int8}})   # time: 0.028393256
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},String})   # time: 0.028013354
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt64}})   # time: 0.027857004
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Float16}})   # time: 0.027637728
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int16}})   # time: 0.027572574
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Float64})   # time: 0.026379427
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Float32}})   # time: 0.02543505
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt32}})   # time: 0.025302937
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:header_crayon, :subheader_crayon), Tuple{Vector{Crayon}, Vector{Crayon}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.024867965
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt32,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.023570292
    Base.precompile(Tuple{Core.kwftype(typeof(_rm_row_name_column_title)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :row_name_column_title, :row_names, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, String, Vector{String}, Symbol, Vector{Int64}}},typeof(_rm_row_name_column_title)})   # time: 0.023520894
    Base.precompile(Tuple{Core.kwftype(typeof(_rm_row_names)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :row_names, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, Vector{String}, Symbol, Vector{Int64}}},typeof(_rm_row_names)})   # time: 0.023450231
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Bool})   # time: 0.02279727
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int32}})   # time: 0.022364045
    Base.precompile(Tuple{Core.kwftype(typeof(_print_info)),NamedTuple{(:alignment, :cell_alignment, :cell_first_line_only, :compact_printing, :formatters, :header, :header_alignment, :header_cell_alignment, :max_num_of_columns, :max_num_of_rows, :limit_printing, :renderer, :row_labels, :row_label_alignment, :row_label_column_title, :row_number_alignment, :row_number_column_title, :show_header, :show_row_number, :show_subheader, :title, :title_alignment), Tuple{Vector{Symbol}, Nothing, Bool, Bool, Nothing, Tuple{Vector{Symbol}, Vector{String}}, Symbol, Nothing, Int64, Int64, Bool, Symbol, Vector{String}, Symbol, String, Symbol, String, Bool, Bool, Bool, String, Symbol}},typeof(_print_info),ColumnTable})   # time: 0.022202147
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt16}})   # time: 0.021934962
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int64})   # time: 0.021874093
    Base.precompile(Tuple{typeof(_pt_latex),IOContext{Base.TTY},PrintInfo})   # time: 0.021717515
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Float64}})   # time: 0.020760953
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt32}})   # time: 0.02046222
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Tuple{Int64, Int64}})   # time: 0.020435598
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{String}})   # time: 0.019988904
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt8}})   # time: 0.019950652
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Bool}})   # time: 0.019748025
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Float16}})   # time: 0.019598229
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int64}})   # time: 0.019590156
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int16}})   # time: 0.019521298
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Float32}})   # time: 0.01947444
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt8}})   # time: 0.019270975
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int8})   # time: 0.018979905
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt32}})   # time: 0.018890854
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Symbol})   # time: 0.018691618
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt64})   # time: 0.018631615
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt8}})   # time: 0.01838172
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Char}})   # time: 0.018339073
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Float64}})   # time: 0.018167544
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int16}})   # time: 0.01799552
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Float16})   # time: 0.017986527
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Float16}})   # time: 0.017859314
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Bool})   # time: 0.017575443
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Char})   # time: 0.017322578
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt16})   # time: 0.01730349
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Char}})   # time: 0.017286463
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Float32}})   # time: 0.017277258
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{String}})   # time: 0.016942887
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{String}})   # time: 0.016807804
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},HtmlCell{String}})   # time: 0.016610855
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Float32}})   # time: 0.016593263
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int32}})   # time: 0.01648202
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int8}})   # time: 0.016469054
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Char}})   # time: 0.016425328
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int8}})   # time: 0.016409839
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt8})   # time: 0.01638361
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt8}})   # time: 0.016354967
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt64}})   # time: 0.016345432
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Bool}})   # time: 0.016260933
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt16}})   # time: 0.016125554
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int32})   # time: 0.015938679
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int64})   # time: 0.015926654
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Float16}})   # time: 0.015891192
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt64}})   # time: 0.015868403
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int16})   # time: 0.01582237
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int64}})   # time: 0.015807185
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:sortkeys,), Tuple{Bool}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.015793942
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Float16})   # time: 0.015768483
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Float32})   # time: 0.015761822
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Float64}})   # time: 0.01567616
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Float64})   # time: 0.015618954
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt32}})   # time: 0.015605241
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int32}})   # time: 0.014284197
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{String}})   # time: 0.01415576
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Char}})   # time: 0.013580345
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:crop,), Tuple{Symbol}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.013333068
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Symbol})   # time: 0.013297488
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int16})   # time: 0.013192649
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt8})   # time: 0.013159489
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt16})   # time: 0.013124792
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Char})   # time: 0.012809911
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int64}})   # time: 0.012298393
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int64}})   # time: 0.011621782
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Float32})   # time: 0.010391562
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int32})   # time: 0.009982667
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int8})   # time: 0.009364351
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt64})   # time: 0.009304899
    Base.precompile(Tuple{Core.kwftype(typeof(pretty_table)),NamedTuple{(:backend,), Tuple{Val{:html}}},typeof(pretty_table),Vector{Any}})   # time: 0.008940173
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UrlTextCell,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.007941717
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,AnsiTextCell,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.006720701
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.006317653
    Base.precompile(Tuple{Core.kwftype(typeof(_rm_row_name_alignment)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :row_name_alignment, :row_name_column_title, :row_names, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, Symbol, String, Vector{String}, Symbol, Vector{Int64}}},typeof(_rm_row_name_alignment)})   # time: 0.006146285
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Tuple{Int64, Int64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.005551141
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt16,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.005485723
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Float64,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.005293927
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,String,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.005059185
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},String})   # time: 0.004954659
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004848328
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int32,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004838198
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Float64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004829172
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Char},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004727774
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int8,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004724601
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004703303
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004654893
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004652272
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Float32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004633313
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt8,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004629931
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Symbol,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004619457
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004570686
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004569108
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Float64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004511123
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Char},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004502513
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004450723
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt64,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004396523
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004385792
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004349805
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004332777
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{String},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.00430429
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Float16,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004265006
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Bool},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004241624
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{String},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004241149
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Float16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004225902
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int64,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004190865
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Bool,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004152127
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004143262
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004121098
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Float16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.0040759
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Bool},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004071312
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004067128
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004058234
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int16,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004036854
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004032817
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Float32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004025332
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Float32,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003992519
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Char,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003941072
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Symbol})   # time: 0.003694652
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UrlTextCell})   # time: 0.002688819
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},String})   # time: 0.001814205
    Base.precompile(Tuple{typeof(_print_custom_text_cell!),Display,UrlTextCell,String,Crayon,Int64,Ref{Any}})   # time: 0.001487795
    Base.precompile(Tuple{typeof(_print_custom_text_cell!),Display,AnsiTextCell,String,Crayon,Int64,Ref{Any}})   # time: 0.001266912
end
