function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{Core.kwftype(typeof(pretty_table)),NamedTuple{(:alignment, :crop), Tuple{Symbol, Symbol}},typeof(pretty_table),Vector{Any}})   # time: 0.09166629
    Base.precompile(Tuple{typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.06306479
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},AnsiTextCell})   # time: 0.04918001
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_latex)),NamedTuple{(:compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Val{:print}}},typeof(_parse_cell_latex),IOContext{Base.TTY},String})   # time: 0.04736495
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},String})   # time: 0.042312283
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int8}})   # time: 0.04129249
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, Symbol, Vector{Int64}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.037530437
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{String}})   # time: 0.033564217
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Tuple{Int64, Int64}})   # time: 0.03086925
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_html)),NamedTuple{(:header_cell_titles, :minify, :show_omitted_cell_summary, :standalone, :table_class, :table_div_class, :top_left_str, :top_right_str_decoration, :vcrop_mode, :wrap_table_in_div), Tuple{Tuple{Nothing, Vector{String}}, Bool, Bool, Bool, String, String, String, HtmlDecoration, Symbol, Bool}},typeof(_pt_html),IOContext{Base.TTY},PrintInfo})   # time: 0.03058846
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt64}})   # time: 0.030177135
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Float32}})   # time: 0.02838473
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Float16})   # time: 0.02772932
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Bool}})   # time: 0.02729206
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_latex)),NamedTuple{(:cell_first_line_only, :compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_latex),IOContext{Base.TTY},LatexCell{String}})   # time: 0.027082436
    Base.precompile(Tuple{typeof(_pt_html),IOContext{Base.TTY},PrintInfo})   # time: 0.02686522
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Float16}})   # time: 0.026457898
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int64}})   # time: 0.026385792
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:subheader_crayon,), Tuple{Vector{Crayon}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.026378136
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{String}})   # time: 0.026327102
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt64}})   # time: 0.026145102
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Float64}})   # time: 0.025054697
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt64}})   # time: 0.024925636
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Char})   # time: 0.024275133
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int8}})   # time: 0.024129758
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int16}})   # time: 0.022888048
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt32}})   # time: 0.02287563
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:header_crayon,), Tuple{Vector{Crayon}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.022154052
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt16}})   # time: 0.02094123
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:header_crayon, :subheader_crayon), Tuple{Vector{Crayon}, Vector{Crayon}}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.020715049
    Base.precompile(Tuple{Core.kwftype(typeof(_rm_row_names)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :row_names, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, Vector{String}, Symbol, Vector{Int64}}},typeof(_rm_row_names)})   # time: 0.020392518
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},String})   # time: 0.020379897
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.019298576
    Base.precompile(Tuple{Core.kwftype(typeof(_print_info)),NamedTuple{(:alignment, :cell_alignment, :cell_first_line_only, :compact_printing, :formatters, :header, :header_alignment, :header_cell_alignment, :max_num_of_columns, :max_num_of_rows, :limit_printing, :renderer, :row_labels, :row_label_alignment, :row_label_column_title, :row_number_alignment, :row_number_column_title, :show_header, :show_row_number, :show_subheader, :title, :title_alignment), Tuple{Vector{Symbol}, Nothing, Bool, Bool, Nothing, Tuple{Vector{Symbol}, Vector{String}}, Symbol, Nothing, Int64, Int64, Bool, Symbol, Vector{String}, Symbol, String, Symbol, String, Bool, Bool, Bool, String, Symbol}},typeof(_print_info),ColumnTable})   # time: 0.019049775
    Base.precompile(Tuple{Core.kwftype(typeof(_rm_row_name_column_title)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :row_name_column_title, :row_names, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, String, Vector{String}, Symbol, Vector{Int64}}},typeof(_rm_row_name_column_title)})   # time: 0.019012796
    Base.precompile(Tuple{typeof(_print_table_data!),Display,ProcessedTable,Matrix{Vector{String}},Vector{Int64},Int64,Vector{Int64},Int64,Vector{Int64},NTuple{4, Char},Symbol,Int64,Ref{Any},Vector{Int64},TextFormat,TextCrayons{Crayon, Crayon},Symbol})   # time: 0.018050278
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},HtmlCell{String}})   # time: 0.016651688
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :compact_printing, :limit_printing, :renderer), Tuple{Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Symbol})   # time: 0.016106216
    Base.precompile(Tuple{typeof(_pt_latex),IOContext{Base.TTY},PrintInfo})   # time: 0.015397309
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Float64}})   # time: 0.013915408
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Bool}})   # time: 0.013878357
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int64})   # time: 0.013640724
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Char}})   # time: 0.013578926
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt8}})   # time: 0.013247371
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int8})   # time: 0.013201072
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int32}})   # time: 0.013156948
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Float16}})   # time: 0.013140557
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int16}})   # time: 0.013098765
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Float16}})   # time: 0.01307611
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt16}})   # time: 0.01303954
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Float16}})   # time: 0.013015033
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Float32}})   # time: 0.012990926
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Char}})   # time: 0.012983397
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Float32}})   # time: 0.012971094
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int16})   # time: 0.012887663
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int8}})   # time: 0.012848368
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt16}})   # time: 0.012787869
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Float64}})   # time: 0.012661251
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Float32})   # time: 0.012651286
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt32}})   # time: 0.012584226
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{UInt8}})   # time: 0.012567675
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Char})   # time: 0.012536988
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int16}})   # time: 0.01253243
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Float32}})   # time: 0.012511606
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt32}})   # time: 0.012502495
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int32}})   # time: 0.012464652
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt64})   # time: 0.012427973
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Float64})   # time: 0.012408648
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Bool})   # time: 0.012376158
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Char}})   # time: 0.012370245
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{UInt64}})   # time: 0.012368095
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{UInt8}})   # time: 0.012297766
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int32})   # time: 0.012227252
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int32}})   # time: 0.012216771
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt32}})   # time: 0.012209323
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{String}})   # time: 0.012207124
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{String}})   # time: 0.012193873
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int32}})   # time: 0.012193181
    Base.precompile(Tuple{typeof(_print_table_data!),Display,ProcessedTable,Matrix{Vector{String}},Vector{Int64},Int64,Vector{Int64},Int64,Vector{Int64},NTuple{4, Char},Symbol,Int64,Ref{Any},Vector{Int64},TextFormat,TextCrayons{Crayon, Vector{Crayon}},Symbol})   # time: 0.01218863
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt8})   # time: 0.012163906
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Bool}})   # time: 0.012126868
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt16}})   # time: 0.012108057
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{UInt8}})   # time: 0.012087706
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Int64}})   # time: 0.012084104
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int8}})   # time: 0.012081914
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Bool}})   # time: 0.012047783
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt16})   # time: 0.01200808
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},UInt32})   # time: 0.011977414
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Float64}})   # time: 0.011961301
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Vector{Int16}})   # time: 0.01195982
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Matrix{Char}})   # time: 0.011955927
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},Int64})   # time: 0.011952089
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:sortkeys,), Tuple{Bool}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.011847909
    Base.precompile(Tuple{typeof(_print_table_data!),Display,ProcessedTable,Matrix{Vector{String}},Vector{Int64},Int64,Vector{Int64},Int64,Vector{Int64},NTuple{4, Char},Symbol,Int64,Ref{Any},Vector{Int64},TextFormat,TextCrayons{Vector{Crayon}, Vector{Crayon}},Symbol})   # time: 0.011779748
    Base.precompile(Tuple{typeof(_print_table_data!),Display,ProcessedTable,Matrix{Vector{String}},Vector{Int64},Int64,Vector{Int64},Int64,Vector{Int64},NTuple{4, Char},Symbol,Int64,Ref{Any},Vector{Int64},TextFormat,TextCrayons{Vector{Crayon}, Crayon},Symbol})   # time: 0.01159178
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Symbol})   # time: 0.011553833
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Matrix{Int64}})   # time: 0.01153564
    Base.precompile(Tuple{Core.kwftype(typeof(_pt_text)),NamedTuple{(:crop,), Tuple{Symbol}},typeof(_pt_text),IOContext{Base.TTY},PrintInfo})   # time: 0.011105755
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int16})   # time: 0.011083755
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int8})   # time: 0.009392838
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Float32})   # time: 0.009368157
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Float64})   # time: 0.009086464
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Bool})   # time: 0.008839782
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Vector{Int64}})   # time: 0.008795106
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt32})   # time: 0.008739772
    Base.precompile(Tuple{Core.kwftype(typeof(pretty_table)),NamedTuple{(:backend,), Tuple{Val{:html}}},typeof(pretty_table),Vector{Any}})   # time: 0.008729163
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt8})   # time: 0.008650702
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt64})   # time: 0.008641024
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UInt16})   # time: 0.008475896
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Float16})   # time: 0.008363312
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Int32})   # time: 0.008331748
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UrlTextCell,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.005880894
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,AnsiTextCell,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.005387291
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Char,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004846479
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},String})   # time: 0.004723304
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004618938
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Bool},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004227541
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Symbol,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004215802
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Bool},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004204309
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004203732
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Tuple{Int64, Int64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004180089
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004177611
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004122993
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Float16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004119855
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Float64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004112412
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Float32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004096651
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004085723
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{UInt16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004075728
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004042048
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Char},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004023174
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004011185
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt8,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.004007654
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt32,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003995846
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Float16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.00398388
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Char},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003955681
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003946277
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt16},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003939153
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int8,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003924507
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{String},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003923054
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003918175
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int16,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003914686
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Float16,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.00390472
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003901548
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{UInt8},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.00390148
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Float64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003898103
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Float32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003896985
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{Int64},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003887925
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Matrix{String},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003882622
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int32,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003880553
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Float64,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003878668
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt64,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003868262
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Float32,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003856864
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Vector{Int32},String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003824399
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,UInt16,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003818621
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Int64,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003816352
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,String,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003814299
    Base.precompile(Tuple{typeof(_process_data_cell_text),ProcessedTable,Bool,String,Int64,Int64,Int64,Int64,Crayon,Symbol,Ref{Any}})   # time: 0.003810089
    Base.precompile(Tuple{Core.kwftype(typeof(_rm_row_name_alignment)),NamedTuple{(:row_label_crayon, :reserved_display_lines, :crop, :display_size, :ellipsis_line_skip, :hlines, :newline_at_end, :row_name_alignment, :row_name_column_title, :row_names, :vcrop_mode, :vlines), Tuple{Crayon, Int64, Symbol, Tuple{Int64, Int64}, Int64, Vector{Symbol}, Bool, Symbol, String, Vector{String}, Symbol, Vector{Int64}}},typeof(_rm_row_name_alignment)})   # time: 0.003654376
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},UrlTextCell})   # time: 0.002843954
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_text)),NamedTuple{(:autowrap, :cell_data_type, :cell_first_line_only, :column_width, :compact_printing, :has_color, :limit_printing, :linebreaks, :renderer), Tuple{Bool, DataType, Bool, Int64, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_text),IOContext{Base.TTY},Symbol})   # time: 0.002429584
    Base.precompile(Tuple{Core.kwftype(typeof(_parse_cell_html)),NamedTuple{(:allow_html_in_cells, :cell_first_line_only, :compact_printing, :limit_printing, :linebreaks, :renderer), Tuple{Bool, Bool, Bool, Bool, Bool, Val{:print}}},typeof(_parse_cell_html),IOContext{Base.TTY},String})   # time: 0.001561284
    Base.precompile(Tuple{typeof(_print_custom_text_cell!),Display,UrlTextCell,String,Crayon,Int64,Ref{Any}})   # time: 0.00119732
    Base.precompile(Tuple{typeof(_print_custom_text_cell!),Display,AnsiTextCell,String,Crayon,Int64,Ref{Any}})   # time: 0.001193179
end
